# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "client" do |client|
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.0.28"
    client.vm.provider "libvirt" do |kvm|
      kvm.memory = "512"
      kvm.cpus = 1
    end
  end
end
