# -*- mode: ruby -*-
# vi: set ft=ruby :


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Using Ubuntu 14.04
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #  # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end


  # Forwarding port 8080 to local 8080.
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  #Calling bootstrap setup
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
	GO_VERSION=1.5.1
	echo 'Updating and installing Ubuntu packages...'
	sudo apt-get -qq update 
	sudo apt-get -qq upgrade -y
	echo 'Downloading Golang Binary'
	wget https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz -nv
	echo 'Installing GoLang'
	sudo tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz
	echo 'Setting up environment variables'
	echo "export GOPATH=/vagrant/" >> /home/vagrant/.bashrc
	echo "export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin" >> /home/vagrant/.bashrc
SHELL

end
